// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzp_0LJltljHx8guDd7kUdPNgbIDbAteY',
    appId: '1:676127802096:web:845c7b6486d0cd2df4b835',
    messagingSenderId: '676127802096',
    projectId: 'joizone',
    authDomain: 'joizone.firebaseapp.com',
    storageBucket: 'joizone.firebasestorage.app',
    measurementId: 'G-6PY4LTX2NZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuEKsEbYxnzAMMb6zSW3cTFZ2KT3_if_E',
    appId: '1:676127802096:android:4eff7926f70ad240f4b835',
    messagingSenderId: '676127802096',
    projectId: 'joizone',
    storageBucket: 'joizone.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhB4-8ZSTryx6dyF5eQIWk2LSyhaBPhNs',
    appId: '1:676127802096:ios:74f4a5c25125727bf4b835',
    messagingSenderId: '676127802096',
    projectId: 'joizone',
    storageBucket: 'joizone.firebasestorage.app',
    iosBundleId: 'com.example.joizone',
  );
}
